name: Qt Windows Shared

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  Qt_minor_version: 5.15
  Qt_patch_version: 5.15.19
  openssl_location: C:\Program Files\OpenSSL
  sevenzip_location: C:\Program Files\7-Zip
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Rename OpenSSL libraries
        shell: cmd
        run: |
          ren "${{ env.openssl_location }}\lib\VC\x64\MD\libcrypto.lib" libcrypto64MD.lib
          ren "${{ env.openssl_location }}\lib\VC\x64\MD\libssl.lib" libssl64MD.lib
          ren "${{ env.openssl_location }}\lib\VC\x64\MDd\libcrypto.lib" libcrypto64MDd.lib
          ren "${{ env.openssl_location }}\lib\VC\x64\MDd\libssl.lib" libssl64MDd.lib
          
      - name: Install Visual Studio platform toolset v141
        shell: cmd
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe" modify --quiet --norestart --includeRecommended --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --channelId VisualStudio.15.Release --add Microsoft.VisualStudio.Component.VC.v141.x86.x64
          
      - name: Download Qt ${{ env.Qt_patch_version }}
        shell: pwsh
        run: |
          $AllProtocols = [System.Net.SecurityProtocolType]'Tls,Tls11,Tls12'
          [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
          
          $ProgressPreference = 'SilentlyContinue'
          $qt_archive_file = "C:\" + "qt-everywhere-opensource-src-${{ env.Qt_patch_version }}" + ".tar.xz"
          Invoke-WebRequest -Uri https://download.qt.io/archive/qt/${{ env.Qt_minor_version }}/${{ env.Qt_patch_version }}/single/qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz -OutFile $qt_archive_file
          
      - name: Extract Qt ${{ env.Qt_patch_version }}
        working-directory: ${{ env.sevenzip_location }}
        shell: cmd
        run: |
          7z x C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz -oC:\
          7z x C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar -oC:\
          del C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz
          del C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar
          
      - name: Install Ninja
        shell: pwsh
        run: choco install ninja

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.16
      - name: Configure Qt ${{ env.Qt_patch_version }}
        working-directory: C:/qt-everywhere-src-${{ env.Qt_patch_version }}
        shell: cmd
        run: |
          configure.bat ^
          -opensource ^
          -confirm-license ^
          -debug-and-release ^
          -shared ^
          -platform win32-msvc ^
          -mp ^
          -gif ^
          -qt-libjpeg ^
          -qt-libpng ^
          -qt-webp ^
          -nomake examples ^
          -nomake tests ^
          -no-compile-examples ^
          -no-dbus ^
          -no-accessibility ^
          -qt-doubleconversion ^
          -no-icu ^
          -openssl-linked OPENSSL_LIBS="-lUser32 -lAdvapi32 -lGdi32 -lCrypt32 -lWs2_32" OPENSSL_PREFIX="${{ env.openssl_location }}" OPENSSL_LIBS_RELEASE="-llibcrypto64MD -llibssl64MD" OPENSSL_LIBS_DEBUG="-llibcrypto64MDd -llibssl64MDd" ^
          -I "${{ env.openssl_location }}\include" ^
          -L "${{ env.openssl_location }}\lib\VC\x64\MD" ^
          -L "${{ env.openssl_location }}\lib\VC\x64\MDd" ^
          -L "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib" ^
          -no-schannel ^
          -no-securetransport ^
          -no-cups ^
          -no-fontconfig ^
          -no-freetype ^
          -no-harfbuzz ^
          -no-gtk ^
          -no-opengl ^
          -no-direct2d ^
          -no-eglfs ^
          -no-ico ^
          -no-sql-db2 ^
          -no-sql-ibase ^
          -no-sql-mysql ^
          -no-sql-oci ^
          -no-sql-odbc ^
          -no-sql-psql ^
          -no-sql-sqlite ^
          -no-sql-sqlite2 ^
          -no-sql-tds ^
          -no-tiff ^
          -no-feature-sqlmodel ^
          -no-feature-testlib_selfcover ^
          -no-feature-textmarkdownreader ^
          -no-feature-textmarkdownwriter ^
          -no-feature-textodfwriter ^
          -no-feature-printer ^
          -skip qt3d ^
          -skip qtactiveqt ^
          -skip qtandroidextras ^
          -skip qtcanvas3d ^
          -skip qtcharts ^
          -skip qtconnectivity ^
          -skip qtdatavis3d ^
          -skip qtdeclarative ^
          -skip qtdoc ^
          -skip qtfeedback ^
          -skip qtgamepad ^
          -skip qtgraphicaleffects ^
          -skip qtlocation ^
          -skip qtlottie ^
          -skip qtmacextras ^
          -skip qtnetworkauth ^
          -skip qtpim ^
          -skip qtpurchasing ^
          -skip qtqa ^
          -skip qtquick3d ^
          -skip qtquickcontrols ^
          -skip qtquickcontrols2 ^
          -skip qtquicktimeline ^
          -skip qtremoteobjects ^
          -skip qtrepotools ^
          -skip qtscript ^
          -skip qtscxml ^
          -skip qtsensors ^
          -skip qtserialbus ^
          -skip qtserialport ^
          -skip qtspeech ^
          -skip qtsystems ^
          -skip qttools ^
          -skip qttranslations ^
          -skip qtvirtualkeyboard ^
          -skip qtwayland ^
          -skip qtwebchannel ^
          -skip qtwebengine ^
          -skip qtwebglplugin ^
          -skip qtwebsockets ^
          -skip qtwebview ^
          -skip qtwinextras ^
          -skip qtx11extras ^
          -skip qtxmlpatterns

      - name: Build Qt ${{ env.Qt_patch_version }}
        working-directory: C:/qt-everywhere-src-${{ env.Qt_patch_version }}
        shell: pwsh
        run: nmake
          
      - name: Install Qt ${{ env.Qt_patch_version }}
        working-directory: C:/qt-everywhere-src-${{ env.Qt_patch_version }}
        shell: pwsh
        run: nmake install

      - name: Upload Qt library to GitHub repo
        working-directory: C:/
        env:
          PAT: ${{ secrets.PAT }}
        shell: cmd
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ github.repository_owner }}@example.com"
          git init
          git add Qt
          git commit -m "Initial commit"
          git branch -M main
          git remote add origin https://"%PAT%"@github.com/${{ github.repository_owner }}/Qt-Win-Shared.git
          git remote -v
          git push origin main

      - name: Copy the config file
        shell: cmd
        run: copy "C:\qt-everywhere-src-${{ env.Qt_patch_version }}\config.summary" "C:\Qt\Qt-${{ env.Qt_patch_version }}\"

      - name: Copy OpenSSL files
        shell: cmd
        run: |
          copy "${{ env.openssl_location }}\bin\libcrypto-3-x64.dll" "C:\Qt\Qt-${{ env.Qt_patch_version }}\bin"
          copy "${{ env.openssl_location }}\bin\libssl-3-x64.dll" "C:\Qt\Qt-${{ env.Qt_patch_version }}\bin"

      - name: Download Qt
        uses: actions/upload-artifact@v7
        with:
          name: Qt-Win-${{ env.Qt_patch_version }}-Shared
          path: C:/Qt/Qt-${{ env.Qt_patch_version }}
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1
